<table id="employee_list_table">
  <tr>
    <th>Email</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>ID</th>
  </tr>

//<?php foreach ($this->entries as $entry): ?>
  <tr>
    <td>//<?php echo $this->escape($entry->email) ?></td>
    <td>//<?php echo $this->escape($entry->firstname) ?></td>
    <td>//<?php echo $this->escape($entry->lastname) ?></td>
  </tr>
//<?php endforeach ?>

</table>