    <!-- application/layouts/scripts/layout.phtml -->
    <?php echo $this->doctype() ?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Zend Framework Quickstart Application</title>
      <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    </head>
    <body>
        <h1>My Company Portal</h1>
         <div id="menu">
           <ul>
             <li><a href="<?php echo $this->url(
                   array('controller' => 'index'), 'default', true) ?>"
                   >Home</a></li>
             <li><a href="<?php echo $this->url(
                   array('controller' => 'employee'), 'default', true) ?>"
                   >Employee Administration</a></li>
           </ul>
         </div>
         <div id="content">
           <?php echo $this->layout()->content; ?>
         </div>
     
    </body>
    </html>